/*
 * generated by Xtext
 */
package org.ow2.fractal.mind.xtext;

import org.eclipse.xtext.ui.common.editor.syntaxcoloring.ILexicalHighlightingConfiguration;
import org.eclipse.xtext.ui.common.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.common.editor.syntaxcoloring.ISemanticHighlightingConfiguration;
import org.eclipse.xtext.ui.common.editor.syntaxcoloring.antlr.AbstractAntlrTokenToAttributeIdMapper;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FractalUiModule extends org.ow2.fractal.mind.xtext.AbstractFractalUiModule {

	/**
	 * register syntax coloring
	 * @return class which define MIND ADL syntax coloring
	 */
	public Class<? extends ILexicalHighlightingConfiguration> bindILexicalHighlightingConfiguration() {
		return LexicalHighlightingConfiguration.class;
		}
	
	/**
	 * register mapping tokens to IDs
	 * @return MIND ADL tokens mapping
	 */
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindTokenToAttributeIdMapper() {
		return AntlrTokenToAttributeIdMapper.class;
		}
	
	/**
	 * 
	 * @return class which define the token that will be highlighted
	 */
	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
		    return SemanticHighlightingCalculator.class;
		}

	
	/**
	 * 
	 * @return class which define color for ID's
	 */
	public Class<? extends ISemanticHighlightingConfiguration> bindSemanticHighlightingConfiguration() {
		    return SemanticHighlightingConfiguration.class;
		}
	
	
	
}
