/*
* generated by Xtext
*/
package org.ow2.fractal.mind.xtext.parser.antlr;

import org.antlr.runtime.ANTLRInputStream;
import org.eclipse.xtext.parser.antlr.ITokenDefProvider;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import org.ow2.fractal.mind.xtext.services.FractalGrammarAccess;

public class FractalParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject 
    protected ITokenDefProvider antlrTokenDefProvider;
	
	@Inject
	private FractalGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, ANTLRInputStream in) {
		org.ow2.fractal.mind.xtext.parser.antlr.internal.InternalFractalLexer lexer = new org.ow2.fractal.mind.xtext.parser.antlr.internal.InternalFractalLexer(in);
		XtextTokenStream stream = new XtextTokenStream(lexer, antlrTokenDefProvider);
		stream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
		org.ow2.fractal.mind.xtext.parser.antlr.internal.InternalFractalParser parser = new org.ow2.fractal.mind.xtext.parser.antlr.internal.InternalFractalParser(
				stream, getElementFactory(), grammarAccess);
		parser.setTokenTypeMap(antlrTokenDefProvider.getTokenDefMap());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AdlDefinition";
	}
	
	public FractalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FractalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
