/*
* generated by Xtext
*/
package org.ow2.fractal.mind.xtext.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.CharStream;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.common.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.common.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.common.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.ow2.fractal.mind.xtext.services.FractalGrammarAccess;

public class FractalParser extends AbstractContentAssistParser {
	
	@Inject
	private FractalGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.ow2.fractal.mind.xtext.contentassist.antlr.internal.InternalFractalLexer createLexer(CharStream stream) {
		return new org.ow2.fractal.mind.xtext.contentassist.antlr.internal.InternalFractalLexer(stream);
	}
	
	@Override
	protected org.ow2.fractal.mind.xtext.contentassist.antlr.internal.InternalFractalParser createParser() {
		org.ow2.fractal.mind.xtext.contentassist.antlr.internal.InternalFractalParser result = new org.ow2.fractal.mind.xtext.contentassist.antlr.internal.InternalFractalParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				{
					put(grammarAccess.getArchitectureDefinitionAccess().getAlternatives(), "rule__ArchitectureDefinition__Alternatives");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getAlternatives_5(), "rule__PrimitiveComponentDefinition__Alternatives_5");
					put(grammarAccess.getPrimitiveDefinitionElementAccess().getAlternatives_0(), "rule__PrimitiveDefinitionElement__Alternatives_0");
					put(grammarAccess.getComponentTypeDefinitionAccess().getAlternatives_3(), "rule__ComponentTypeDefinition__Alternatives_3");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getAlternatives_5(), "rule__CompositeComponentDefinition__Alternatives_5");
					put(grammarAccess.getCompositeDefinitionElementAccess().getAlternatives_0(), "rule__CompositeDefinitionElement__Alternatives_0");
					put(grammarAccess.getSubComponentDefinitionAccess().getAlternatives_1(), "rule__SubComponentDefinition__Alternatives_1");
					put(grammarAccess.getTemplateDefinitionAccess().getAlternatives_1(), "rule__TemplateDefinition__Alternatives_1");
					put(grammarAccess.getBindingDefinitionAccess().getAlternatives_1(), "rule__BindingDefinition__Alternatives_1");
					put(grammarAccess.getBindingDefinitionAccess().getAlternatives_6(), "rule__BindingDefinition__Alternatives_6");
					put(grammarAccess.getDataDefinitionAccess().getAlternatives(), "rule__DataDefinition__Alternatives");
					put(grammarAccess.getDataDefinitionAccess().getAlternatives_0_1(), "rule__DataDefinition__Alternatives_0_1");
					put(grammarAccess.getImplementationDefinitionAccess().getAlternatives_1(), "rule__ImplementationDefinition__Alternatives_1");
					put(grammarAccess.getElementValueAccess().getAlternatives(), "rule__ElementValue__Alternatives");
					put(grammarAccess.getConstantFormatAccess().getAlternatives(), "rule__ConstantFormat__Alternatives");
					put(grammarAccess.getCodeCAccess().getAlternatives(), "rule__CodeC__Alternatives");
					put(grammarAccess.getPathAccess().getAlternatives_2_0(), "rule__Path__Alternatives_2_0");
					put(grammarAccess.getPathAccess().getAlternatives_3(), "rule__Path__Alternatives_3");
					put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
					put(grammarAccess.getAnnotationTypeAccess().getAlternatives(), "rule__AnnotationType__Alternatives");
					put(grammarAccess.getAttributeTypeAccess().getAlternatives(), "rule__AttributeType__Alternatives");
					put(grammarAccess.getContingencyAccess().getAlternatives(), "rule__Contingency__Alternatives");
					put(grammarAccess.getRoleAccess().getAlternatives(), "rule__Role__Alternatives");
					put(grammarAccess.getAdlDefinitionAccess().getGroup(), "rule__AdlDefinition__Group__0");
					put(grammarAccess.getImportDefinitionAccess().getGroup(), "rule__ImportDefinition__Group__0");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getGroup(), "rule__PrimitiveComponentDefinition__Group__0");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getGroup_5_0(), "rule__PrimitiveComponentDefinition__Group_5_0__0");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getGroup_5_0_1(), "rule__PrimitiveComponentDefinition__Group_5_0_1__0");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getGroup_5_1(), "rule__PrimitiveComponentDefinition__Group_5_1__0");
					put(grammarAccess.getPrimitiveDefinitionElementAccess().getGroup(), "rule__PrimitiveDefinitionElement__Group__0");
					put(grammarAccess.getComponentTypeDefinitionAccess().getGroup(), "rule__ComponentTypeDefinition__Group__0");
					put(grammarAccess.getComponentTypeDefinitionAccess().getGroup_3_0(), "rule__ComponentTypeDefinition__Group_3_0__0");
					put(grammarAccess.getComponentTypeDefinitionAccess().getGroup_3_1(), "rule__ComponentTypeDefinition__Group_3_1__0");
					put(grammarAccess.getComponentTypeDefinitionAccess().getGroup_3_1_1(), "rule__ComponentTypeDefinition__Group_3_1_1__0");
					put(grammarAccess.getTypeReferencesListAccess().getGroup(), "rule__TypeReferencesList__Group__0");
					put(grammarAccess.getTypeReferencesListAccess().getGroup_2(), "rule__TypeReferencesList__Group_2__0");
					put(grammarAccess.getTypeDefinitionElementAccess().getGroup(), "rule__TypeDefinitionElement__Group__0");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getGroup(), "rule__CompositeComponentDefinition__Group__0");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getGroup_5_0(), "rule__CompositeComponentDefinition__Group_5_0__0");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getGroup_5_0_1(), "rule__CompositeComponentDefinition__Group_5_0_1__0");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getGroup_5_1(), "rule__CompositeComponentDefinition__Group_5_1__0");
					put(grammarAccess.getTemplateSpecifiersListAccess().getGroup(), "rule__TemplateSpecifiersList__Group__0");
					put(grammarAccess.getTemplateSpecifiersListAccess().getGroup_1(), "rule__TemplateSpecifiersList__Group_1__0");
					put(grammarAccess.getTemplateSpecifiersListAccess().getGroup_1_1(), "rule__TemplateSpecifiersList__Group_1_1__0");
					put(grammarAccess.getFormalArgumentsListAccess().getGroup(), "rule__FormalArgumentsList__Group__0");
					put(grammarAccess.getFormalArgumentsListAccess().getGroup_1(), "rule__FormalArgumentsList__Group_1__0");
					put(grammarAccess.getFormalArgumentsListAccess().getGroup_1_1(), "rule__FormalArgumentsList__Group_1_1__0");
					put(grammarAccess.getCompositeReferencesListAccess().getGroup(), "rule__CompositeReferencesList__Group__0");
					put(grammarAccess.getCompositeReferencesListAccess().getGroup_2(), "rule__CompositeReferencesList__Group_2__0");
					put(grammarAccess.getPrimitiveReferencesListAccess().getGroup(), "rule__PrimitiveReferencesList__Group__0");
					put(grammarAccess.getPrimitiveReferencesListAccess().getGroup_2(), "rule__PrimitiveReferencesList__Group_2__0");
					put(grammarAccess.getCompositeDefinitionElementAccess().getGroup(), "rule__CompositeDefinitionElement__Group__0");
					put(grammarAccess.getSubComponentDefinitionAccess().getGroup(), "rule__SubComponentDefinition__Group__0");
					put(grammarAccess.getCompositeReferenceDefinitionAccess().getGroup(), "rule__CompositeReferenceDefinition__Group__0");
					put(grammarAccess.getCompositeReferenceDefinitionAccess().getGroup_1(), "rule__CompositeReferenceDefinition__Group_1__0");
					put(grammarAccess.getCompositeReferenceDefinitionAccess().getGroup_1_2(), "rule__CompositeReferenceDefinition__Group_1_2__0");
					put(grammarAccess.getCompositeReferenceDefinitionAccess().getGroup_2(), "rule__CompositeReferenceDefinition__Group_2__0");
					put(grammarAccess.getCompositeReferenceDefinitionAccess().getGroup_2_2(), "rule__CompositeReferenceDefinition__Group_2_2__0");
					put(grammarAccess.getCompositeSubComponentAccess().getGroup(), "rule__CompositeSubComponent__Group__0");
					put(grammarAccess.getCompositeAnonymousSubComponentAccess().getGroup(), "rule__CompositeAnonymousSubComponent__Group__0");
					put(grammarAccess.getCompositeAnonymousSubComponentAccess().getGroup_5(), "rule__CompositeAnonymousSubComponent__Group_5__0");
					put(grammarAccess.getPrimitiveReferenceDefinitionAccess().getGroup(), "rule__PrimitiveReferenceDefinition__Group__0");
					put(grammarAccess.getPrimitiveReferenceDefinitionAccess().getGroup_1(), "rule__PrimitiveReferenceDefinition__Group_1__0");
					put(grammarAccess.getPrimitiveReferenceDefinitionAccess().getGroup_1_2(), "rule__PrimitiveReferenceDefinition__Group_1_2__0");
					put(grammarAccess.getTemplateDefinitionAccess().getGroup(), "rule__TemplateDefinition__Group__0");
					put(grammarAccess.getTemplateDefinitionAccess().getGroup_0(), "rule__TemplateDefinition__Group_0__0");
					put(grammarAccess.getTemplateSubComponentAccess().getGroup(), "rule__TemplateSubComponent__Group__0");
					put(grammarAccess.getPrimitiveSubComponentAccess().getGroup(), "rule__PrimitiveSubComponent__Group__0");
					put(grammarAccess.getPrimitiveAnonymousSubComponentAccess().getGroup(), "rule__PrimitiveAnonymousSubComponent__Group__0");
					put(grammarAccess.getPrimitiveAnonymousSubComponentAccess().getGroup_5(), "rule__PrimitiveAnonymousSubComponent__Group_5__0");
					put(grammarAccess.getAttributeDefinitionAccess().getGroup(), "rule__AttributeDefinition__Group__0");
					put(grammarAccess.getAttributeDefinitionAccess().getGroup_3(), "rule__AttributeDefinition__Group_3__0");
					put(grammarAccess.getArgumentDefinitionAccess().getGroup(), "rule__ArgumentDefinition__Group__0");
					put(grammarAccess.getArgumentDefinitionAccess().getGroup_0(), "rule__ArgumentDefinition__Group_0__0");
					put(grammarAccess.getInterfaceDefinitionAccess().getGroup(), "rule__InterfaceDefinition__Group__0");
					put(grammarAccess.getInterfaceDefinitionAccess().getGroup_4(), "rule__InterfaceDefinition__Group_4__0");
					put(grammarAccess.getBindingDefinitionAccess().getGroup(), "rule__BindingDefinition__Group__0");
					put(grammarAccess.getBindingDefinitionAccess().getGroup_4(), "rule__BindingDefinition__Group_4__0");
					put(grammarAccess.getBindingDefinitionAccess().getGroup_9(), "rule__BindingDefinition__Group_9__0");
					put(grammarAccess.getDataDefinitionAccess().getGroup_0(), "rule__DataDefinition__Group_0__0");
					put(grammarAccess.getDataDefinitionAccess().getGroup_0_1_1(), "rule__DataDefinition__Group_0_1_1__0");
					put(grammarAccess.getImplementationDefinitionAccess().getGroup(), "rule__ImplementationDefinition__Group__0");
					put(grammarAccess.getImplementationDefinitionAccess().getGroup_1_1(), "rule__ImplementationDefinition__Group_1_1__0");
					put(grammarAccess.getTemplateSpecifierAccess().getGroup(), "rule__TemplateSpecifier__Group__0");
					put(grammarAccess.getFullyQualifiedNameAccess().getGroup(), "rule__FullyQualifiedName__Group__0");
					put(grammarAccess.getFullyQualifiedNameAccess().getGroup_1(), "rule__FullyQualifiedName__Group_1__0");
					put(grammarAccess.getFileCAccess().getGroup(), "rule__FileC__Group__0");
					put(grammarAccess.getFilenameAccess().getGroup(), "rule__Filename__Group__0");
					put(grammarAccess.getAnnotationsListAccess().getGroup(), "rule__AnnotationsList__Group__0");
					put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
					put(grammarAccess.getAnnotationAccess().getGroup_2(), "rule__Annotation__Group_2__0");
					put(grammarAccess.getAnnotationAccess().getGroup_2_2(), "rule__Annotation__Group_2_2__0");
					put(grammarAccess.getAnnotationElementAccess().getGroup(), "rule__AnnotationElement__Group__0");
					put(grammarAccess.getAnnotationElementAccess().getGroup_0(), "rule__AnnotationElement__Group_0__0");
					put(grammarAccess.getElementValueArrayInitializerAccess().getGroup(), "rule__ElementValueArrayInitializer__Group__0");
					put(grammarAccess.getElementValueArrayInitializerAccess().getGroup_2(), "rule__ElementValueArrayInitializer__Group_2__0");
					put(grammarAccess.getPathAccess().getGroup(), "rule__Path__Group__0");
					put(grammarAccess.getPathAccess().getGroup_2(), "rule__Path__Group_2__0");
					put(grammarAccess.getAdlDefinitionAccess().getImportsAssignment_0(), "rule__AdlDefinition__ImportsAssignment_0");
					put(grammarAccess.getAdlDefinitionAccess().getDefinitionAnnotationsListAssignment_1(), "rule__AdlDefinition__DefinitionAnnotationsListAssignment_1");
					put(grammarAccess.getAdlDefinitionAccess().getArchitecturedefinitionAssignment_2(), "rule__AdlDefinition__ArchitecturedefinitionAssignment_2");
					put(grammarAccess.getImportDefinitionAccess().getImportNameAssignment_1(), "rule__ImportDefinition__ImportNameAssignment_1");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getAbstractAssignment_0(), "rule__PrimitiveComponentDefinition__AbstractAssignment_0");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getNameAssignment_2(), "rule__PrimitiveComponentDefinition__NameAssignment_2");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getPrimitiveFormalArgumentsListAssignment_3(), "rule__PrimitiveComponentDefinition__PrimitiveFormalArgumentsListAssignment_3");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getPrimitiveReferencesListAssignment_4(), "rule__PrimitiveComponentDefinition__PrimitiveReferencesListAssignment_4");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getPrimitiveElementsAssignment_5_0_1_0(), "rule__PrimitiveComponentDefinition__PrimitiveElementsAssignment_5_0_1_0");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getPrimitiveElementsAssignment_5_0_1_1(), "rule__PrimitiveComponentDefinition__PrimitiveElementsAssignment_5_0_1_1");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getPrimitiveElementsAssignment_5_1_0(), "rule__PrimitiveComponentDefinition__PrimitiveElementsAssignment_5_1_0");
					put(grammarAccess.getPrimitiveComponentDefinitionAccess().getPrimitiveElementsAssignment_5_1_1(), "rule__PrimitiveComponentDefinition__PrimitiveElementsAssignment_5_1_1");
					put(grammarAccess.getComponentTypeDefinitionAccess().getNameAssignment_1(), "rule__ComponentTypeDefinition__NameAssignment_1");
					put(grammarAccess.getComponentTypeDefinitionAccess().getTypeReferencesListAssignment_2(), "rule__ComponentTypeDefinition__TypeReferencesListAssignment_2");
					put(grammarAccess.getComponentTypeDefinitionAccess().getTypeElementsAssignment_3_0_0(), "rule__ComponentTypeDefinition__TypeElementsAssignment_3_0_0");
					put(grammarAccess.getComponentTypeDefinitionAccess().getTypeElementsAssignment_3_0_1(), "rule__ComponentTypeDefinition__TypeElementsAssignment_3_0_1");
					put(grammarAccess.getComponentTypeDefinitionAccess().getTypeElementsAssignment_3_1_1_0(), "rule__ComponentTypeDefinition__TypeElementsAssignment_3_1_1_0");
					put(grammarAccess.getComponentTypeDefinitionAccess().getTypeElementsAssignment_3_1_1_1(), "rule__ComponentTypeDefinition__TypeElementsAssignment_3_1_1_1");
					put(grammarAccess.getTypeReferencesListAccess().getTypeReferencesAssignment_1(), "rule__TypeReferencesList__TypeReferencesAssignment_1");
					put(grammarAccess.getTypeReferencesListAccess().getTypeReferencesAssignment_2_1(), "rule__TypeReferencesList__TypeReferencesAssignment_2_1");
					put(grammarAccess.getTypeReferenceDefinitionAccess().getReferenceNameAssignment(), "rule__TypeReferenceDefinition__ReferenceNameAssignment");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getNameAssignment_1(), "rule__CompositeComponentDefinition__NameAssignment_1");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getTemplateSpecifiersListAssignment_2(), "rule__CompositeComponentDefinition__TemplateSpecifiersListAssignment_2");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getCompositeFormalArgumentsListAssignment_3(), "rule__CompositeComponentDefinition__CompositeFormalArgumentsListAssignment_3");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getCompositeReferencesListAssignment_4(), "rule__CompositeComponentDefinition__CompositeReferencesListAssignment_4");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getCompositeElementsAssignment_5_0_1_0(), "rule__CompositeComponentDefinition__CompositeElementsAssignment_5_0_1_0");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getCompositeElementsAssignment_5_0_1_1(), "rule__CompositeComponentDefinition__CompositeElementsAssignment_5_0_1_1");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getCompositeElementsAssignment_5_1_0(), "rule__CompositeComponentDefinition__CompositeElementsAssignment_5_1_0");
					put(grammarAccess.getCompositeComponentDefinitionAccess().getCompositeElementsAssignment_5_1_1(), "rule__CompositeComponentDefinition__CompositeElementsAssignment_5_1_1");
					put(grammarAccess.getTemplateSpecifiersListAccess().getTemplateSpecifiersAssignment_1_0(), "rule__TemplateSpecifiersList__TemplateSpecifiersAssignment_1_0");
					put(grammarAccess.getTemplateSpecifiersListAccess().getTemplateSpecifiersAssignment_1_1_1(), "rule__TemplateSpecifiersList__TemplateSpecifiersAssignment_1_1_1");
					put(grammarAccess.getFormalArgumentsListAccess().getFormalArgumentsAssignment_1_0(), "rule__FormalArgumentsList__FormalArgumentsAssignment_1_0");
					put(grammarAccess.getFormalArgumentsListAccess().getFormalArgumentsAssignment_1_1_1(), "rule__FormalArgumentsList__FormalArgumentsAssignment_1_1_1");
					put(grammarAccess.getCompositeReferencesListAccess().getCompositeReferencesAssignment_1(), "rule__CompositeReferencesList__CompositeReferencesAssignment_1");
					put(grammarAccess.getCompositeReferencesListAccess().getCompositeReferencesAssignment_2_1(), "rule__CompositeReferencesList__CompositeReferencesAssignment_2_1");
					put(grammarAccess.getPrimitiveReferencesListAccess().getPrimitiveReferencesAssignment_1(), "rule__PrimitiveReferencesList__PrimitiveReferencesAssignment_1");
					put(grammarAccess.getPrimitiveReferencesListAccess().getPrimitiveReferencesAssignment_2_1(), "rule__PrimitiveReferencesList__PrimitiveReferencesAssignment_2_1");
					put(grammarAccess.getFormalArgumentAccess().getNameAssignment(), "rule__FormalArgument__NameAssignment");
					put(grammarAccess.getCompositeReferenceDefinitionAccess().getReferenceNameAssignment_0(), "rule__CompositeReferenceDefinition__ReferenceNameAssignment_0");
					put(grammarAccess.getCompositeReferenceDefinitionAccess().getTemplatesListAssignment_1_1(), "rule__CompositeReferenceDefinition__TemplatesListAssignment_1_1");
					put(grammarAccess.getCompositeReferenceDefinitionAccess().getTemplatesListAssignment_1_2_1(), "rule__CompositeReferenceDefinition__TemplatesListAssignment_1_2_1");
					put(grammarAccess.getCompositeReferenceDefinitionAccess().getArgumentsListAssignment_2_1(), "rule__CompositeReferenceDefinition__ArgumentsListAssignment_2_1");
					put(grammarAccess.getCompositeReferenceDefinitionAccess().getArgumentsListAssignment_2_2_1(), "rule__CompositeReferenceDefinition__ArgumentsListAssignment_2_2_1");
					put(grammarAccess.getCompositeSubComponentAccess().getCompositeReferenceDefinitionAssignment_1(), "rule__CompositeSubComponent__CompositeReferenceDefinitionAssignment_1");
					put(grammarAccess.getCompositeSubComponentAccess().getNameAssignment_3(), "rule__CompositeSubComponent__NameAssignment_3");
					put(grammarAccess.getCompositeAnonymousSubComponentAccess().getCompositeReferenceDefinitionAssignment_1(), "rule__CompositeAnonymousSubComponent__CompositeReferenceDefinitionAssignment_1");
					put(grammarAccess.getCompositeAnonymousSubComponentAccess().getNameAssignment_3(), "rule__CompositeAnonymousSubComponent__NameAssignment_3");
					put(grammarAccess.getCompositeAnonymousSubComponentAccess().getCompositeElementsAssignment_5_0(), "rule__CompositeAnonymousSubComponent__CompositeElementsAssignment_5_0");
					put(grammarAccess.getCompositeAnonymousSubComponentAccess().getCompositeElementsAssignment_5_1(), "rule__CompositeAnonymousSubComponent__CompositeElementsAssignment_5_1");
					put(grammarAccess.getPrimitiveReferenceDefinitionAccess().getReferenceNameAssignment_0(), "rule__PrimitiveReferenceDefinition__ReferenceNameAssignment_0");
					put(grammarAccess.getPrimitiveReferenceDefinitionAccess().getArgumentsListAssignment_1_1(), "rule__PrimitiveReferenceDefinition__ArgumentsListAssignment_1_1");
					put(grammarAccess.getPrimitiveReferenceDefinitionAccess().getArgumentsListAssignment_1_2_1(), "rule__PrimitiveReferenceDefinition__ArgumentsListAssignment_1_2_1");
					put(grammarAccess.getTemplateDefinitionAccess().getTemplateNameAssignment_0_0(), "rule__TemplateDefinition__TemplateNameAssignment_0_0");
					put(grammarAccess.getTemplateDefinitionAccess().getTemplateValueAssignment_1_0(), "rule__TemplateDefinition__TemplateValueAssignment_1_0");
					put(grammarAccess.getTemplateSubComponentAccess().getTemplateReferenceDefinitionAssignment_0(), "rule__TemplateSubComponent__TemplateReferenceDefinitionAssignment_0");
					put(grammarAccess.getTemplateSubComponentAccess().getNameAssignment_2(), "rule__TemplateSubComponent__NameAssignment_2");
					put(grammarAccess.getPrimitiveSubComponentAccess().getPrimitiveReferenceDefinitionAssignment_1(), "rule__PrimitiveSubComponent__PrimitiveReferenceDefinitionAssignment_1");
					put(grammarAccess.getPrimitiveSubComponentAccess().getNameAssignment_3(), "rule__PrimitiveSubComponent__NameAssignment_3");
					put(grammarAccess.getPrimitiveAnonymousSubComponentAccess().getPrimitiveReferenceDefinitionAssignment_1(), "rule__PrimitiveAnonymousSubComponent__PrimitiveReferenceDefinitionAssignment_1");
					put(grammarAccess.getPrimitiveAnonymousSubComponentAccess().getNameAssignment_3(), "rule__PrimitiveAnonymousSubComponent__NameAssignment_3");
					put(grammarAccess.getPrimitiveAnonymousSubComponentAccess().getPrimitiveElementsAssignment_5_0(), "rule__PrimitiveAnonymousSubComponent__PrimitiveElementsAssignment_5_0");
					put(grammarAccess.getPrimitiveAnonymousSubComponentAccess().getPrimitiveElementsAssignment_5_1(), "rule__PrimitiveAnonymousSubComponent__PrimitiveElementsAssignment_5_1");
					put(grammarAccess.getAttributeDefinitionAccess().getTypeAssignment_1(), "rule__AttributeDefinition__TypeAssignment_1");
					put(grammarAccess.getAttributeDefinitionAccess().getAttributeNameAssignment_2(), "rule__AttributeDefinition__AttributeNameAssignment_2");
					put(grammarAccess.getAttributeDefinitionAccess().getValueAssignment_3_1(), "rule__AttributeDefinition__ValueAssignment_3_1");
					put(grammarAccess.getArgumentDefinitionAccess().getArgumentNameAssignment_0_0(), "rule__ArgumentDefinition__ArgumentNameAssignment_0_0");
					put(grammarAccess.getArgumentDefinitionAccess().getArgumentValueAssignment_1(), "rule__ArgumentDefinition__ArgumentValueAssignment_1");
					put(grammarAccess.getInterfaceDefinitionAccess().getRoleAssignment_0(), "rule__InterfaceDefinition__RoleAssignment_0");
					put(grammarAccess.getInterfaceDefinitionAccess().getSignatureAssignment_1(), "rule__InterfaceDefinition__SignatureAssignment_1");
					put(grammarAccess.getInterfaceDefinitionAccess().getNameAssignment_3(), "rule__InterfaceDefinition__NameAssignment_3");
					put(grammarAccess.getInterfaceDefinitionAccess().getCollectionAssignment_4_0(), "rule__InterfaceDefinition__CollectionAssignment_4_0");
					put(grammarAccess.getInterfaceDefinitionAccess().getCollectionsizeAssignment_4_1(), "rule__InterfaceDefinition__CollectionsizeAssignment_4_1");
					put(grammarAccess.getInterfaceDefinitionAccess().getCollectionAssignment_4_2(), "rule__InterfaceDefinition__CollectionAssignment_4_2");
					put(grammarAccess.getInterfaceDefinitionAccess().getContingencyAssignment_5(), "rule__InterfaceDefinition__ContingencyAssignment_5");
					put(grammarAccess.getBindingDefinitionAccess().getInterfaceSourceParentAssignment_1_1(), "rule__BindingDefinition__InterfaceSourceParentAssignment_1_1");
					put(grammarAccess.getBindingDefinitionAccess().getInterfaceSourceAssignment_3(), "rule__BindingDefinition__InterfaceSourceAssignment_3");
					put(grammarAccess.getBindingDefinitionAccess().getInterfaceSourceIndexAssignment_4_1(), "rule__BindingDefinition__InterfaceSourceIndexAssignment_4_1");
					put(grammarAccess.getBindingDefinitionAccess().getInterfaceTargetParentAssignment_6_1(), "rule__BindingDefinition__InterfaceTargetParentAssignment_6_1");
					put(grammarAccess.getBindingDefinitionAccess().getInterfaceTargetAssignment_8(), "rule__BindingDefinition__InterfaceTargetAssignment_8");
					put(grammarAccess.getBindingDefinitionAccess().getInterfaceTargetIndexAssignment_9_1(), "rule__BindingDefinition__InterfaceTargetIndexAssignment_9_1");
					put(grammarAccess.getDataDefinitionAccess().getFileCAssignment_0_1_0(), "rule__DataDefinition__FileCAssignment_0_1_0");
					put(grammarAccess.getDataDefinitionAccess().getInlineCcodeAssignment_0_1_1_1(), "rule__DataDefinition__InlineCcodeAssignment_0_1_1_1");
					put(grammarAccess.getImplementationDefinitionAccess().getFileCAssignment_1_0(), "rule__ImplementationDefinition__FileCAssignment_1_0");
					put(grammarAccess.getImplementationDefinitionAccess().getInlineCcodeAssignment_1_1_1(), "rule__ImplementationDefinition__InlineCcodeAssignment_1_1_1");
					put(grammarAccess.getTemplateSpecifierAccess().getNameAssignment_0(), "rule__TemplateSpecifier__NameAssignment_0");
					put(grammarAccess.getTemplateSpecifierAccess().getComponentTypeNameAssignment_2(), "rule__TemplateSpecifier__ComponentTypeNameAssignment_2");
					put(grammarAccess.getFileCAccess().getDirectoryAssignment_0(), "rule__FileC__DirectoryAssignment_0");
					put(grammarAccess.getFileCAccess().getFileNameAssignment_1(), "rule__FileC__FileNameAssignment_1");
					put(grammarAccess.getInlineCodeCAccess().getCodeCAssignment(), "rule__InlineCodeC__CodeCAssignment");
					put(grammarAccess.getAnnotationsListAccess().getAnnotationsAssignment_0(), "rule__AnnotationsList__AnnotationsAssignment_0");
					put(grammarAccess.getAnnotationsListAccess().getAnnotationsAssignment_1(), "rule__AnnotationsList__AnnotationsAssignment_1");
					put(grammarAccess.getAnnotationAccess().getNameAssignment_1(), "rule__Annotation__NameAssignment_1");
					put(grammarAccess.getAnnotationAccess().getAnnotationElementsAssignment_2_1(), "rule__Annotation__AnnotationElementsAssignment_2_1");
					put(grammarAccess.getAnnotationAccess().getAnnotationElementsAssignment_2_2_1(), "rule__Annotation__AnnotationElementsAssignment_2_2_1");
					put(grammarAccess.getAnnotationElementAccess().getElementNameAssignment_0_0(), "rule__AnnotationElement__ElementNameAssignment_0_0");
					put(grammarAccess.getAnnotationElementAccess().getElementValueAssignment_1(), "rule__AnnotationElement__ElementValueAssignment_1");
					put(grammarAccess.getConstantValueAccess().getValueAssignment(), "rule__ConstantValue__ValueAssignment");
					put(grammarAccess.getElementValueArrayInitializerAccess().getValuesAssignment_1(), "rule__ElementValueArrayInitializer__ValuesAssignment_1");
					put(grammarAccess.getElementValueArrayInitializerAccess().getValuesAssignment_2_1(), "rule__ElementValueArrayInitializer__ValuesAssignment_2_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.ow2.fractal.mind.xtext.contentassist.antlr.internal.InternalFractalParser typedParser = (org.ow2.fractal.mind.xtext.contentassist.antlr.internal.InternalFractalParser) parser;
			typedParser.entryRuleAdlDefinition();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public FractalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FractalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
