
/*
 * generated by Xtext
 */
 
package org.ow2.mind.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class AdlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.ow2.mind.ui.internal.AdlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.ow2.mind.ui.internal.AdlActivator.getInstance().getInjector("org.ow2.mind.Adl");
	}
	
}
