/*
 * generated by Xtext
 */
package org.ow2.fractal.mind.xtext;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FractalRuntimeModule extends org.ow2.fractal.mind.xtext.AbstractFractalRuntimeModule {

}
