/*
* generated by Xtext
*/
package org.ow2.mind.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.ow2.mind.services.AdlGrammarAccess;

public class AdlParser extends AbstractContentAssistParser {
	
	@Inject
	private AdlGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.ow2.mind.ui.contentassist.antlr.internal.InternalAdlParser createParser() {
		org.ow2.mind.ui.contentassist.antlr.internal.InternalAdlParser result = new org.ow2.mind.ui.contentassist.antlr.internal.InternalAdlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDefinitionAccess().getAlternatives(), "rule__Definition__Alternatives");
					put(grammarAccess.getParametricDefinitionAccess().getAlternatives(), "rule__ParametricDefinition__Alternatives");
					put(grammarAccess.getTypeDefinitionAccess().getAlternatives_5(), "rule__TypeDefinition__Alternatives_5");
					put(grammarAccess.getPrimitiveDefinitionAccess().getAlternatives_7(), "rule__PrimitiveDefinition__Alternatives_7");
					put(grammarAccess.getPrimitiveDefinitionAccess().getContentAlternatives_7_0_1_0_0(), "rule__PrimitiveDefinition__ContentAlternatives_7_0_1_0_0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getContentAlternatives_7_1_0_0(), "rule__PrimitiveDefinition__ContentAlternatives_7_1_0_0");
					put(grammarAccess.getCompositeDefinitionAccess().getAlternatives_7(), "rule__CompositeDefinition__Alternatives_7");
					put(grammarAccess.getCompositeDefinitionAccess().getContentAlternatives_7_0_1_0_0(), "rule__CompositeDefinition__ContentAlternatives_7_0_1_0_0");
					put(grammarAccess.getCompositeDefinitionAccess().getContentAlternatives_7_1_0_0(), "rule__CompositeDefinition__ContentAlternatives_7_1_0_0");
					put(grammarAccess.getDefinitionOrTemplateAccess().getAlternatives(), "rule__DefinitionOrTemplate__Alternatives");
					put(grammarAccess.getTemplateParameterAccess().getAlternatives(), "rule__TemplateParameter__Alternatives");
					put(grammarAccess.getParameterAccess().getAlternatives(), "rule__Parameter__Alternatives");
					put(grammarAccess.getParameterValueAccess().getAlternatives(), "rule__ParameterValue__Alternatives");
					put(grammarAccess.getContentAccess().getAlternatives(), "rule__Content__Alternatives");
					put(grammarAccess.getInterfaceAccess().getAlternatives(), "rule__Interface__Alternatives");
					put(grammarAccess.getTypeInterfaceAccess().getAlternatives(), "rule__TypeInterface__Alternatives");
					put(grammarAccess.getFlowInterfaceAccess().getAlternatives(), "rule__FlowInterface__Alternatives");
					put(grammarAccess.getFlowTypeAccess().getAlternatives(), "rule__FlowType__Alternatives");
					put(grammarAccess.getAttributeValueAccess().getAlternatives(), "rule__AttributeValue__Alternatives");
					put(grammarAccess.getDataAccess().getAlternatives_2(), "rule__Data__Alternatives_2");
					put(grammarAccess.getSourceAccess().getAlternatives_2(), "rule__Source__Alternatives_2");
					put(grammarAccess.getImplementationAccess().getAlternatives(), "rule__Implementation__Alternatives");
					put(grammarAccess.getAnonymousDefinitionAccess().getAlternatives(), "rule__AnonymousDefinition__Alternatives");
					put(grammarAccess.getAbstractDefinitionAccess().getAlternatives(), "rule__AbstractDefinition__Alternatives");
					put(grammarAccess.getPrimitiveAnonymousDefinitionAccess().getContentAlternatives_4_0_0(), "rule__PrimitiveAnonymousDefinition__ContentAlternatives_4_0_0");
					put(grammarAccess.getCompositeAnonymousDefinitionAccess().getContentAlternatives_4_0_0(), "rule__CompositeAnonymousDefinition__ContentAlternatives_4_0_0");
					put(grammarAccess.getBindingAccess().getAlternatives_2(), "rule__Binding__Alternatives_2");
					put(grammarAccess.getBindingAccess().getAlternatives_7(), "rule__Binding__Alternatives_7");
					put(grammarAccess.getAnnotationAccess().getAlternatives_2_1(), "rule__Annotation__Alternatives_2_1");
					put(grammarAccess.getAnnotationValueAccess().getAlternatives(), "rule__AnnotationValue__Alternatives");
					put(grammarAccess.getAnnotationContainerAccess().getAlternatives(), "rule__AnnotationContainer__Alternatives");
					put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
					put(grammarAccess.getNullLiteralAccess().getAlternatives(), "rule__NullLiteral__Alternatives");
					put(grammarAccess.getBooleanLiteralAccess().getAlternatives(), "rule__BooleanLiteral__Alternatives");
					put(grammarAccess.getQualifiedNameWithWildCardAccess().getAlternatives_3(), "rule__QualifiedNameWithWildCard__Alternatives_3");
					put(grammarAccess.getFlowTypeKindAccess().getAlternatives(), "rule__FlowTypeKind__Alternatives");
					put(grammarAccess.getAttributeTypeAccess().getAlternatives(), "rule__AttributeType__Alternatives");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getTypeDefinitionAccess().getGroup(), "rule__TypeDefinition__Group__0");
					put(grammarAccess.getTypeDefinitionAccess().getGroup_4(), "rule__TypeDefinition__Group_4__0");
					put(grammarAccess.getTypeDefinitionAccess().getGroup_4_2(), "rule__TypeDefinition__Group_4_2__0");
					put(grammarAccess.getTypeDefinitionAccess().getGroup_5_0(), "rule__TypeDefinition__Group_5_0__0");
					put(grammarAccess.getTypeDefinitionAccess().getGroup_5_0_1(), "rule__TypeDefinition__Group_5_0_1__0");
					put(grammarAccess.getTypeDefinitionAccess().getGroup_5_1(), "rule__TypeDefinition__Group_5_1__0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getGroup(), "rule__PrimitiveDefinition__Group__0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getGroup_5(), "rule__PrimitiveDefinition__Group_5__0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getGroup_5_1(), "rule__PrimitiveDefinition__Group_5_1__0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getGroup_5_1_1(), "rule__PrimitiveDefinition__Group_5_1_1__0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getGroup_6(), "rule__PrimitiveDefinition__Group_6__0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getGroup_6_2(), "rule__PrimitiveDefinition__Group_6_2__0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getGroup_7_0(), "rule__PrimitiveDefinition__Group_7_0__0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getGroup_7_0_1(), "rule__PrimitiveDefinition__Group_7_0_1__0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getGroup_7_1(), "rule__PrimitiveDefinition__Group_7_1__0");
					put(grammarAccess.getCompositeDefinitionAccess().getGroup(), "rule__CompositeDefinition__Group__0");
					put(grammarAccess.getCompositeDefinitionAccess().getGroup_4(), "rule__CompositeDefinition__Group_4__0");
					put(grammarAccess.getCompositeDefinitionAccess().getGroup_4_1(), "rule__CompositeDefinition__Group_4_1__0");
					put(grammarAccess.getCompositeDefinitionAccess().getGroup_4_1_1(), "rule__CompositeDefinition__Group_4_1_1__0");
					put(grammarAccess.getCompositeDefinitionAccess().getGroup_5(), "rule__CompositeDefinition__Group_5__0");
					put(grammarAccess.getCompositeDefinitionAccess().getGroup_5_1(), "rule__CompositeDefinition__Group_5_1__0");
					put(grammarAccess.getCompositeDefinitionAccess().getGroup_5_1_1(), "rule__CompositeDefinition__Group_5_1_1__0");
					put(grammarAccess.getCompositeDefinitionAccess().getGroup_6(), "rule__CompositeDefinition__Group_6__0");
					put(grammarAccess.getCompositeDefinitionAccess().getGroup_6_2(), "rule__CompositeDefinition__Group_6_2__0");
					put(grammarAccess.getCompositeDefinitionAccess().getGroup_7_0(), "rule__CompositeDefinition__Group_7_0__0");
					put(grammarAccess.getCompositeDefinitionAccess().getGroup_7_0_1(), "rule__CompositeDefinition__Group_7_0_1__0");
					put(grammarAccess.getCompositeDefinitionAccess().getGroup_7_1(), "rule__CompositeDefinition__Group_7_1__0");
					put(grammarAccess.getTemplateParameterDeclAccess().getGroup(), "rule__TemplateParameterDecl__Group__0");
					put(grammarAccess.getDefinitionReferenceAccess().getGroup(), "rule__DefinitionReference__Group__0");
					put(grammarAccess.getDefinitionReferenceAccess().getGroup_1(), "rule__DefinitionReference__Group_1__0");
					put(grammarAccess.getDefinitionReferenceAccess().getGroup_1_2(), "rule__DefinitionReference__Group_1_2__0");
					put(grammarAccess.getDefinitionReferenceAccess().getGroup_2(), "rule__DefinitionReference__Group_2__0");
					put(grammarAccess.getDefinitionReferenceAccess().getGroup_2_2(), "rule__DefinitionReference__Group_2_2__0");
					put(grammarAccess.getTemplateParameterAccess().getGroup_1(), "rule__TemplateParameter__Group_1__0");
					put(grammarAccess.getTemplateParameterAssignmentAccess().getGroup(), "rule__TemplateParameterAssignment__Group__0");
					put(grammarAccess.getParameterAccess().getGroup_1(), "rule__Parameter__Group_1__0");
					put(grammarAccess.getParameterAssignmentAccess().getGroup(), "rule__ParameterAssignment__Group__0");
					put(grammarAccess.getServerInterfaceAccess().getGroup(), "rule__ServerInterface__Group__0");
					put(grammarAccess.getServerInterfaceAccess().getGroup_5(), "rule__ServerInterface__Group_5__0");
					put(grammarAccess.getClientInterfaceAccess().getGroup(), "rule__ClientInterface__Group__0");
					put(grammarAccess.getClientInterfaceAccess().getGroup_6(), "rule__ClientInterface__Group_6__0");
					put(grammarAccess.getInputInterfaceAccess().getGroup(), "rule__InputInterface__Group__0");
					put(grammarAccess.getInputInterfaceAccess().getGroup_6(), "rule__InputInterface__Group_6__0");
					put(grammarAccess.getOutputInterfaceAccess().getGroup(), "rule__OutputInterface__Group__0");
					put(grammarAccess.getOutputInterfaceAccess().getGroup_6(), "rule__OutputInterface__Group_6__0");
					put(grammarAccess.getFlowTypeAccess().getGroup_1(), "rule__FlowType__Group_1__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_4(), "rule__Attribute__Group_4__0");
					put(grammarAccess.getDataAccess().getGroup(), "rule__Data__Group__0");
					put(grammarAccess.getSourceAccess().getGroup(), "rule__Source__Group__0");
					put(grammarAccess.getPathAccess().getGroup(), "rule__Path__Group__0");
					put(grammarAccess.getPathAccess().getGroup_4(), "rule__Path__Group_4__0");
					put(grammarAccess.getSubComponentAccess().getGroup(), "rule__SubComponent__Group__0");
					put(grammarAccess.getPrimitiveAnonymousDefinitionAccess().getGroup(), "rule__PrimitiveAnonymousDefinition__Group__0");
					put(grammarAccess.getPrimitiveAnonymousDefinitionAccess().getGroup_4(), "rule__PrimitiveAnonymousDefinition__Group_4__0");
					put(grammarAccess.getCompositeAnonymousDefinitionAccess().getGroup(), "rule__CompositeAnonymousDefinition__Group__0");
					put(grammarAccess.getCompositeAnonymousDefinitionAccess().getGroup_4(), "rule__CompositeAnonymousDefinition__Group_4__0");
					put(grammarAccess.getBindingAccess().getGroup(), "rule__Binding__Group__0");
					put(grammarAccess.getBindingAccess().getGroup_5(), "rule__Binding__Group_5__0");
					put(grammarAccess.getBindingAccess().getGroup_10(), "rule__Binding__Group_10__0");
					put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
					put(grammarAccess.getAnnotationAccess().getGroup_2(), "rule__Annotation__Group_2__0");
					put(grammarAccess.getAnnotationAccess().getGroup_2_1_1(), "rule__Annotation__Group_2_1_1__0");
					put(grammarAccess.getAnnotationAccess().getGroup_2_1_1_1(), "rule__Annotation__Group_2_1_1_1__0");
					put(grammarAccess.getAnnotationFieldAccess().getGroup(), "rule__AnnotationField__Group__0");
					put(grammarAccess.getArrayValueAccess().getGroup(), "rule__ArrayValue__Group__0");
					put(grammarAccess.getArrayValueAccess().getGroup_2(), "rule__ArrayValue__Group_2__0");
					put(grammarAccess.getArrayValueAccess().getGroup_2_1(), "rule__ArrayValue__Group_2_1__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getQualifiedNameWithWildCardAccess().getGroup(), "rule__QualifiedNameWithWildCard__Group__0");
					put(grammarAccess.getQualifiedNameWithWildCardAccess().getGroup_2(), "rule__QualifiedNameWithWildCard__Group_2__0");
					put(grammarAccess.getImportAccess().getAnnotationsAssignment_0(), "rule__Import__AnnotationsAssignment_0");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_2(), "rule__Import__ImportedNamespaceAssignment_2");
					put(grammarAccess.getTypeDefinitionAccess().getImportsAssignment_0(), "rule__TypeDefinition__ImportsAssignment_0");
					put(grammarAccess.getTypeDefinitionAccess().getAnnotationsAssignment_1(), "rule__TypeDefinition__AnnotationsAssignment_1");
					put(grammarAccess.getTypeDefinitionAccess().getNameAssignment_3(), "rule__TypeDefinition__NameAssignment_3");
					put(grammarAccess.getTypeDefinitionAccess().getExtendsAssignment_4_1(), "rule__TypeDefinition__ExtendsAssignment_4_1");
					put(grammarAccess.getTypeDefinitionAccess().getExtendsAssignment_4_2_1(), "rule__TypeDefinition__ExtendsAssignment_4_2_1");
					put(grammarAccess.getTypeDefinitionAccess().getContentAssignment_5_0_1_0(), "rule__TypeDefinition__ContentAssignment_5_0_1_0");
					put(grammarAccess.getTypeDefinitionAccess().getContentAssignment_5_1_0(), "rule__TypeDefinition__ContentAssignment_5_1_0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getImportsAssignment_0(), "rule__PrimitiveDefinition__ImportsAssignment_0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getAnnotationsAssignment_1(), "rule__PrimitiveDefinition__AnnotationsAssignment_1");
					put(grammarAccess.getPrimitiveDefinitionAccess().getAbstractAssignment_2(), "rule__PrimitiveDefinition__AbstractAssignment_2");
					put(grammarAccess.getPrimitiveDefinitionAccess().getNameAssignment_4(), "rule__PrimitiveDefinition__NameAssignment_4");
					put(grammarAccess.getPrimitiveDefinitionAccess().getParametersAssignment_5_1_0(), "rule__PrimitiveDefinition__ParametersAssignment_5_1_0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getParametersAssignment_5_1_1_1(), "rule__PrimitiveDefinition__ParametersAssignment_5_1_1_1");
					put(grammarAccess.getPrimitiveDefinitionAccess().getExtendsAssignment_6_1(), "rule__PrimitiveDefinition__ExtendsAssignment_6_1");
					put(grammarAccess.getPrimitiveDefinitionAccess().getExtendsAssignment_6_2_1(), "rule__PrimitiveDefinition__ExtendsAssignment_6_2_1");
					put(grammarAccess.getPrimitiveDefinitionAccess().getContentAssignment_7_0_1_0(), "rule__PrimitiveDefinition__ContentAssignment_7_0_1_0");
					put(grammarAccess.getPrimitiveDefinitionAccess().getContentAssignment_7_1_0(), "rule__PrimitiveDefinition__ContentAssignment_7_1_0");
					put(grammarAccess.getParameterDeclAccess().getNameAssignment(), "rule__ParameterDecl__NameAssignment");
					put(grammarAccess.getCompositeDefinitionAccess().getImportsAssignment_0(), "rule__CompositeDefinition__ImportsAssignment_0");
					put(grammarAccess.getCompositeDefinitionAccess().getAnnotationsAssignment_1(), "rule__CompositeDefinition__AnnotationsAssignment_1");
					put(grammarAccess.getCompositeDefinitionAccess().getNameAssignment_3(), "rule__CompositeDefinition__NameAssignment_3");
					put(grammarAccess.getCompositeDefinitionAccess().getTemplateParametersAssignment_4_1_0(), "rule__CompositeDefinition__TemplateParametersAssignment_4_1_0");
					put(grammarAccess.getCompositeDefinitionAccess().getTemplateParametersAssignment_4_1_1_1(), "rule__CompositeDefinition__TemplateParametersAssignment_4_1_1_1");
					put(grammarAccess.getCompositeDefinitionAccess().getParametersAssignment_5_1_0(), "rule__CompositeDefinition__ParametersAssignment_5_1_0");
					put(grammarAccess.getCompositeDefinitionAccess().getParametersAssignment_5_1_1_1(), "rule__CompositeDefinition__ParametersAssignment_5_1_1_1");
					put(grammarAccess.getCompositeDefinitionAccess().getExtendsAssignment_6_1(), "rule__CompositeDefinition__ExtendsAssignment_6_1");
					put(grammarAccess.getCompositeDefinitionAccess().getExtendsAssignment_6_2_1(), "rule__CompositeDefinition__ExtendsAssignment_6_2_1");
					put(grammarAccess.getCompositeDefinitionAccess().getContentAssignment_7_0_1_0(), "rule__CompositeDefinition__ContentAssignment_7_0_1_0");
					put(grammarAccess.getCompositeDefinitionAccess().getContentAssignment_7_1_0(), "rule__CompositeDefinition__ContentAssignment_7_1_0");
					put(grammarAccess.getTemplateParameterDeclAccess().getNameAssignment_0(), "rule__TemplateParameterDecl__NameAssignment_0");
					put(grammarAccess.getTemplateParameterDeclAccess().getTypeAssignment_2(), "rule__TemplateParameterDecl__TypeAssignment_2");
					put(grammarAccess.getDefinitionReferenceAccess().getDefinitionAssignment_0(), "rule__DefinitionReference__DefinitionAssignment_0");
					put(grammarAccess.getDefinitionReferenceAccess().getTemplateParametersAssignment_1_1(), "rule__DefinitionReference__TemplateParametersAssignment_1_1");
					put(grammarAccess.getDefinitionReferenceAccess().getTemplateParametersAssignment_1_2_1(), "rule__DefinitionReference__TemplateParametersAssignment_1_2_1");
					put(grammarAccess.getDefinitionReferenceAccess().getParametersAssignment_2_1(), "rule__DefinitionReference__ParametersAssignment_2_1");
					put(grammarAccess.getDefinitionReferenceAccess().getParametersAssignment_2_2_1(), "rule__DefinitionReference__ParametersAssignment_2_2_1");
					put(grammarAccess.getTemplateParameterAccess().getValueAssignment_1_1(), "rule__TemplateParameter__ValueAssignment_1_1");
					put(grammarAccess.getTemplateParameterAssignmentAccess().getNameAssignment_0(), "rule__TemplateParameterAssignment__NameAssignment_0");
					put(grammarAccess.getTemplateParameterAssignmentAccess().getValueAssignment_2(), "rule__TemplateParameterAssignment__ValueAssignment_2");
					put(grammarAccess.getParameterAccess().getValueAssignment_1_1(), "rule__Parameter__ValueAssignment_1_1");
					put(grammarAccess.getParameterAssignmentAccess().getNameAssignment_0(), "rule__ParameterAssignment__NameAssignment_0");
					put(grammarAccess.getParameterAssignmentAccess().getValueAssignment_2(), "rule__ParameterAssignment__ValueAssignment_2");
					put(grammarAccess.getParameterValueAccess().getLiteralAssignment_0(), "rule__ParameterValue__LiteralAssignment_0");
					put(grammarAccess.getParameterValueAccess().getRefAssignment_1(), "rule__ParameterValue__RefAssignment_1");
					put(grammarAccess.getServerInterfaceAccess().getAnnotationsAssignment_0(), "rule__ServerInterface__AnnotationsAssignment_0");
					put(grammarAccess.getServerInterfaceAccess().getSignatureAssignment_2(), "rule__ServerInterface__SignatureAssignment_2");
					put(grammarAccess.getServerInterfaceAccess().getNameAssignment_4(), "rule__ServerInterface__NameAssignment_4");
					put(grammarAccess.getServerInterfaceAccess().getCollectionAssignment_5_0(), "rule__ServerInterface__CollectionAssignment_5_0");
					put(grammarAccess.getServerInterfaceAccess().getSizeAssignment_5_1(), "rule__ServerInterface__SizeAssignment_5_1");
					put(grammarAccess.getClientInterfaceAccess().getAnnotationsAssignment_0(), "rule__ClientInterface__AnnotationsAssignment_0");
					put(grammarAccess.getClientInterfaceAccess().getOptionalAssignment_2(), "rule__ClientInterface__OptionalAssignment_2");
					put(grammarAccess.getClientInterfaceAccess().getSignatureAssignment_3(), "rule__ClientInterface__SignatureAssignment_3");
					put(grammarAccess.getClientInterfaceAccess().getNameAssignment_5(), "rule__ClientInterface__NameAssignment_5");
					put(grammarAccess.getClientInterfaceAccess().getCollectionAssignment_6_0(), "rule__ClientInterface__CollectionAssignment_6_0");
					put(grammarAccess.getClientInterfaceAccess().getSizeAssignment_6_1(), "rule__ClientInterface__SizeAssignment_6_1");
					put(grammarAccess.getInputInterfaceAccess().getAnnotationsAssignment_0(), "rule__InputInterface__AnnotationsAssignment_0");
					put(grammarAccess.getInputInterfaceAccess().getOptionalAssignment_2(), "rule__InputInterface__OptionalAssignment_2");
					put(grammarAccess.getInputInterfaceAccess().getTypeAssignment_3(), "rule__InputInterface__TypeAssignment_3");
					put(grammarAccess.getInputInterfaceAccess().getNameAssignment_5(), "rule__InputInterface__NameAssignment_5");
					put(grammarAccess.getInputInterfaceAccess().getCollectionAssignment_6_0(), "rule__InputInterface__CollectionAssignment_6_0");
					put(grammarAccess.getInputInterfaceAccess().getSizeAssignment_6_1(), "rule__InputInterface__SizeAssignment_6_1");
					put(grammarAccess.getOutputInterfaceAccess().getAnnotationsAssignment_0(), "rule__OutputInterface__AnnotationsAssignment_0");
					put(grammarAccess.getOutputInterfaceAccess().getOptionalAssignment_2(), "rule__OutputInterface__OptionalAssignment_2");
					put(grammarAccess.getOutputInterfaceAccess().getTypeAssignment_3(), "rule__OutputInterface__TypeAssignment_3");
					put(grammarAccess.getOutputInterfaceAccess().getNameAssignment_5(), "rule__OutputInterface__NameAssignment_5");
					put(grammarAccess.getOutputInterfaceAccess().getCollectionAssignment_6_0(), "rule__OutputInterface__CollectionAssignment_6_0");
					put(grammarAccess.getOutputInterfaceAccess().getSizeAssignment_6_1(), "rule__OutputInterface__SizeAssignment_6_1");
					put(grammarAccess.getFlowTypeAccess().getTypeAssignment_0(), "rule__FlowType__TypeAssignment_0");
					put(grammarAccess.getFlowTypeAccess().getPathAssignment_1_0(), "rule__FlowType__PathAssignment_1_0");
					put(grammarAccess.getFlowTypeAccess().getKindAssignment_1_2(), "rule__FlowType__KindAssignment_1_2");
					put(grammarAccess.getFlowTypeAccess().getNameAssignment_1_3(), "rule__FlowType__NameAssignment_1_3");
					put(grammarAccess.getAttributeAccess().getAnnotationsAssignment_0(), "rule__Attribute__AnnotationsAssignment_0");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_2(), "rule__Attribute__TypeAssignment_2");
					put(grammarAccess.getAttributeAccess().getNameAssignment_3(), "rule__Attribute__NameAssignment_3");
					put(grammarAccess.getAttributeAccess().getValueAssignment_4_1(), "rule__Attribute__ValueAssignment_4_1");
					put(grammarAccess.getAttributeValueAccess().getLiteralAssignment_0(), "rule__AttributeValue__LiteralAssignment_0");
					put(grammarAccess.getAttributeValueAccess().getRefAssignment_1(), "rule__AttributeValue__RefAssignment_1");
					put(grammarAccess.getDataAccess().getAnnotationsAssignment_0(), "rule__Data__AnnotationsAssignment_0");
					put(grammarAccess.getDataAccess().getPathAssignment_2_0(), "rule__Data__PathAssignment_2_0");
					put(grammarAccess.getDataAccess().getInlinedCodeAssignment_2_1(), "rule__Data__InlinedCodeAssignment_2_1");
					put(grammarAccess.getSourceAccess().getAnnotationsAssignment_0(), "rule__Source__AnnotationsAssignment_0");
					put(grammarAccess.getSourceAccess().getPathAssignment_2_0(), "rule__Source__PathAssignment_2_0");
					put(grammarAccess.getSourceAccess().getInlinedCodeAssignment_2_1(), "rule__Source__InlinedCodeAssignment_2_1");
					put(grammarAccess.getSubComponentAccess().getAnnotationsAssignment_0(), "rule__SubComponent__AnnotationsAssignment_0");
					put(grammarAccess.getSubComponentAccess().getTypeAssignment_2(), "rule__SubComponent__TypeAssignment_2");
					put(grammarAccess.getSubComponentAccess().getNameAssignment_4(), "rule__SubComponent__NameAssignment_4");
					put(grammarAccess.getSubComponentAccess().getAnonymousDefAssignment_5(), "rule__SubComponent__AnonymousDefAssignment_5");
					put(grammarAccess.getPrimitiveAnonymousDefinitionAccess().getAnnotationsAssignment_1(), "rule__PrimitiveAnonymousDefinition__AnnotationsAssignment_1");
					put(grammarAccess.getPrimitiveAnonymousDefinitionAccess().getContentAssignment_4_0(), "rule__PrimitiveAnonymousDefinition__ContentAssignment_4_0");
					put(grammarAccess.getCompositeAnonymousDefinitionAccess().getAnnotationsAssignment_1(), "rule__CompositeAnonymousDefinition__AnnotationsAssignment_1");
					put(grammarAccess.getCompositeAnonymousDefinitionAccess().getContentAssignment_4_0(), "rule__CompositeAnonymousDefinition__ContentAssignment_4_0");
					put(grammarAccess.getBindingAccess().getAnnotationsAssignment_0(), "rule__Binding__AnnotationsAssignment_0");
					put(grammarAccess.getBindingAccess().getFromSubCompAssignment_2_0(), "rule__Binding__FromSubCompAssignment_2_0");
					put(grammarAccess.getBindingAccess().getFromItfAssignment_4(), "rule__Binding__FromItfAssignment_4");
					put(grammarAccess.getBindingAccess().getFromIndexAssignment_5_1(), "rule__Binding__FromIndexAssignment_5_1");
					put(grammarAccess.getBindingAccess().getToSubCompAssignment_7_0(), "rule__Binding__ToSubCompAssignment_7_0");
					put(grammarAccess.getBindingAccess().getToItfAssignment_9(), "rule__Binding__ToItfAssignment_9");
					put(grammarAccess.getBindingAccess().getTondexAssignment_10_1(), "rule__Binding__TondexAssignment_10_1");
					put(grammarAccess.getAnnotationAccess().getNameAssignment_1(), "rule__Annotation__NameAssignment_1");
					put(grammarAccess.getAnnotationAccess().getParametersAssignment_2_1_0(), "rule__Annotation__ParametersAssignment_2_1_0");
					put(grammarAccess.getAnnotationAccess().getParametersAssignment_2_1_1_0(), "rule__Annotation__ParametersAssignment_2_1_1_0");
					put(grammarAccess.getAnnotationAccess().getParametersAssignment_2_1_1_1_1(), "rule__Annotation__ParametersAssignment_2_1_1_1_1");
					put(grammarAccess.getAnnotationFieldAccess().getNameAssignment_0(), "rule__AnnotationField__NameAssignment_0");
					put(grammarAccess.getAnnotationFieldAccess().getValueAssignment_2(), "rule__AnnotationField__ValueAssignment_2");
					put(grammarAccess.getSimpleAnnotationFieldAccess().getValueAssignment(), "rule__SimpleAnnotationField__ValueAssignment");
					put(grammarAccess.getAnnotationAnnotationValueAccess().getValueAssignment(), "rule__AnnotationAnnotationValue__ValueAssignment");
					put(grammarAccess.getArrayValueAccess().getValuesAssignment_2_0(), "rule__ArrayValue__ValuesAssignment_2_0");
					put(grammarAccess.getArrayValueAccess().getValuesAssignment_2_1_1(), "rule__ArrayValue__ValuesAssignment_2_1_1");
					put(grammarAccess.getIntegerLiteralAccess().getValueAssignment(), "rule__IntegerLiteral__ValueAssignment");
					put(grammarAccess.getStringLiteralAccess().getValueAssignment(), "rule__StringLiteral__ValueAssignment");
					put(grammarAccess.getNullLiteralAccess().getValueAssignment_0(), "rule__NullLiteral__ValueAssignment_0");
					put(grammarAccess.getNullLiteralAccess().getValueAssignment_1(), "rule__NullLiteral__ValueAssignment_1");
					put(grammarAccess.getBooleanLiteralAccess().getValueAssignment_0(), "rule__BooleanLiteral__ValueAssignment_0");
					put(grammarAccess.getBooleanLiteralAccess().getValueAssignment_1(), "rule__BooleanLiteral__ValueAssignment_1");
					put(grammarAccess.getPathLiteralAccess().getValueAssignment(), "rule__PathLiteral__ValueAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.ow2.mind.ui.contentassist.antlr.internal.InternalAdlParser typedParser = (org.ow2.mind.ui.contentassist.antlr.internal.InternalAdlParser) parser;
			typedParser.entryRuleDefinition();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
