/*
* generated by Xtext
*/
package org.ow2.fractal.mind.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class FractalTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
