<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="stylesheet" type="text/css" href="adl-documentation.css" />
<title></title>
</head>
<body>

<hr/>
<div class="nav_bar">
<ul class="nav_bar_links">
<li>Overview</li>
<li>Package</li>
</ul>
<span class="clear"></span>
</div>
<hr/>

<h1 class="overview-title">$docTitle$</h1>

$shortDocumentation$<br/>

<p><b>See:</b> <a href="#package_description">Description</a>

<table class="summary">
<tr><th>Packages</th></tr>
$packages:{
<tr><td><a href="$it.summaryHtmlFileName$" title="package $it.name$">$it.name$</a></td></tr>
}; separator="\n"$
</table>

<a name="package_description"/>
$documentation$
</body>
</html>